// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return primaryApp;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Primary app configuration (Smart Ticket System)
  static const FirebaseOptions primaryApp = FirebaseOptions(
    apiKey: 'AIzaSyBtVDQhS0UO0csQgzH9131sGgrMpUQdbfk',
    appId: '1:751952618795:android:4b01b0e31e3290a10b116e',
    messagingSenderId: '751952618795',
    projectId: 'smart-ticket-mtc',
    storageBucket: 'smart-ticket-mtc.firebasestorage.app',
    databaseURL: 'https://smart-ticket-mtc-default-rtdb.firebaseio.com',
  );

  // Gyro Comparator app configuration (Secondary app for fraud detection)
  static const FirebaseOptions gyroComparatorApp = FirebaseOptions(
    apiKey: 'AIzaSyBtVDQhS0UO0csQgzH9131sGgrMpUQdbfk',
    appId: '1:751952618795:android:371245ef36b575850b116e',
    messagingSenderId: '751952618795',
    projectId: 'smart-ticket-mtc',
    storageBucket: 'smart-ticket-mtc.firebasestorage.app',
    databaseURL: 'https://smart-ticket-mtc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVDQhS0UO0csQgzH9131sGgrMpUQdbfk',
    appId: '1:751952618795:ios:4b01b0e31e3290a10b116e',
    messagingSenderId: '751952618795',
    projectId: 'smart-ticket-mtc',
    storageBucket: 'smart-ticket-mtc.firebasestorage.app',
    databaseURL: 'https://smart-ticket-mtc-default-rtdb.firebaseio.com',
    iosBundleId: 'com.smart.ticket_system',
  );
}
