name: iOS Build (Ultra Simple)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 45
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Check Flutter
      run: |
        flutter --version
        flutter doctor
        
    - name: Clean and Install
      run: |
        flutter clean
        flutter pub get
        
    - name: Build iOS (No Signing)
      run: |
        flutter build ios --release --no-codesign --no-tree-shake-icons
        
    - name: Create IPA
      run: |
        mkdir -p ipa-output
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -r ../../../ipa-output/SmartTicket.ipa Payload/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: SmartTicket-IPA
        path: ipa-output/SmartTicket.ipa
