name: iOS Build (Fixed)

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version to use'
        required: false
        default: '3.24.3'

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-13
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ github.event.inputs.flutter_version || '3.24.3' }}
        channel: 'stable'
        cache: true
        
    - name: Disable analytics
      run: |
        flutter config --no-analytics
        dart --disable-analytics
        
    - name: Clean project
      run: |
        flutter clean
        rm -rf ios/Pods ios/Podfile.lock ios/.symlinks
        
    - name: Install dependencies
      run: flutter pub get
        
    - name: Setup iOS environment
      run: |
        cd ios
        pod cache clean --all
        arch -x86_64 pod install --repo-update
        cd ..
        
    - name: Build iOS app
      run: |
        flutter build ios --release \
          --no-codesign \
          --split-debug-info=build/debug-info \
          --obfuscate \
          --dart-define=FLUTTER_WEB_USE_SKIA=true
          
    - name: Create IPA
      run: |
        mkdir -p build/ios/ipa
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -R Runner.app Payload/Runner.app
        cd Payload
        zip -r ../SmartTicketMTC.ipa .
        mv ../SmartTicketMTC.ipa ../../ipa/
        cd ../../../
        
    - name: Verify IPA creation
      run: |
        if [ -f "build/ios/ipa/SmartTicketMTC.ipa" ]; then
          echo "✅ IPA created successfully!"
          ls -lh build/ios/ipa/SmartTicketMTC.ipa
          file build/ios/ipa/SmartTicketMTC.ipa
        else
          echo "❌ IPA creation failed!"
          ls -la build/ios/
          exit 1
        fi
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: SmartTicketMTC-iOS-Release
        path: build/ios/ipa/SmartTicketMTC.ipa
        retention-days: 30
        
    - name: Upload debug symbols
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Debug-Symbols
        path: build/debug-info/
        retention-days: 7
