name: iOS Final Attempt

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.16.9'

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-12
    timeout-minutes: 60
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true
        
    - name: Flutter Doctor
      run: |
        flutter doctor -v
        flutter config --no-analytics
        
    - name: Clean Project
      run: |
        flutter clean
        rm -rf ios/Pods
        rm -rf ios/Podfile.lock
        
    - name: Get Dependencies
      run: flutter pub get
      
    - name: Update Podfile
      run: |
        cd ios
        cat > Podfile << 'EOF'
        # Uncomment this line to define a global platform for your project
        platform :ios, '11.0'

        # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
        ENV['COCOAPODS_DISABLE_STATS'] = 'true'

        project 'Runner', {
          'Debug' => :debug,
          'Profile' => :release,
          'Release' => :release,
        }

        def flutter_root
          generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
          unless File.exist?(generated_xcode_build_settings_path)
            raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
          end

          File.foreach(generated_xcode_build_settings_path) do |line|
            matches = line.match(/FLUTTER_ROOT\=(.*)/)
            return matches[1].strip if matches
          end
          raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
        end

        require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

        flutter_ios_podfile_setup

        target 'Runner' do
          use_frameworks!
          use_modular_headers!

          flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
        end

        post_install do |installer|
          installer.pods_project.targets.each do |target|
            flutter_additional_ios_build_settings(target)
          end
        end
        EOF
        
    - name: Install Pods
      run: |
        cd ios
        pod install --repo-update
        
    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign --no-tree-shake-icons
        
    - name: Verify Build
      run: |
        ls -la build/ios/iphoneos/
        if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
          echo "❌ Runner.app not found!"
          exit 1
        fi
        echo "✅ Runner.app found!"
        
    - name: Create IPA
      run: |
        mkdir -p output
        cd build/ios/iphoneos
        mkdir Payload
        cp -R Runner.app Payload/
        zip -r ../../../output/SmartTicketMTC.ipa Payload/
        cd ../../../
        ls -la output/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: SmartTicketMTC-Final
        path: output/SmartTicketMTC.ipa
        retention-days: 30
