name: iOS Debug Build

on:
  workflow_dispatch:

jobs:
  debug-ios:
    name: Debug iOS Build Issues
    runs-on: macos-14
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Show system info
      run: |
        echo "=== System Information ==="
        sw_vers
        xcode-select --print-path
        xcodebuild -version
        pod --version || echo "CocoaPods not found"
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
        
    - name: Flutter diagnostic
      run: |
        echo "=== Flutter Information ==="
        which flutter
        flutter --version
        flutter doctor -v
        flutter config --list
        
    - name: Clean everything
      run: |
        echo "=== Cleaning Project ==="
        flutter clean
        rm -rf ios/Pods
        rm -rf ios/Podfile.lock
        rm -rf ios/.symlinks
        
    - name: Get Flutter dependencies
      run: |
        echo "=== Installing Flutter Dependencies ==="
        flutter pub get
        flutter pub deps
        
    - name: Check iOS project structure
      run: |
        echo "=== iOS Project Structure ==="
        ls -la ios/
        ls -la ios/Runner/
        echo "=== iOS Info.plist ==="
        cat ios/Runner/Info.plist | head -20
        echo "=== iOS Bundle ID ==="
        grep -r "PRODUCT_BUNDLE_IDENTIFIER" ios/ || echo "Bundle ID not found"
        
    - name: Validate Firebase configuration
      run: |
        echo "=== Firebase Configuration ==="
        ls -la ios/Runner/GoogleService-Info.plist || echo "GoogleService-Info.plist not found"
        head -10 ios/Runner/GoogleService-Info.plist || echo "Cannot read plist"
        
    - name: Install CocoaPods dependencies
      run: |
        echo "=== Installing CocoaPods ==="
        cd ios
        pod --version
        pod repo update
        pod install --verbose
        echo "=== Pod Installation Complete ==="
        ls -la Pods/
        
    - name: Try Flutter build (verbose)
      run: |
        echo "=== Attempting Flutter Build ==="
        flutter build ios --release --no-codesign --verbose || {
          echo "=== Build Failed, showing more info ==="
          flutter doctor --verbose
          exit 1
        }
        
    - name: Show build output
      run: |
        echo "=== Build Output ==="
        ls -la build/ios/iphoneos/ || echo "Build output not found"
        
    - name: Create IPA if build succeeded
      run: |
        echo "=== Creating IPA ==="
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload/
          zip -r ../ipa/SmartTicketMTC-Debug.ipa Payload/
          echo "✅ IPA created successfully!"
          ls -la ../ipa/
        else
          echo "❌ Runner.app not found, build may have failed"
          exit 1
        fi
        
    - name: Upload debug logs and IPA
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: iOS-Debug-Output
        path: |
          build/ios/ipa/
          ios/Podfile.lock
        retention-days: 7
